name: Node.js CI

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  GITHUB_USERNAME: sesac-cloud


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::068251041443:role/ecr-githubaction-role
        aws-region: ap-northeast-2  

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - run: npm ci  -> Dockerfile 안에 존재

    # - run: npm run build --if-present  -> 배포판 위한 npm build 당장 필요 x

    - name: Build, tag, and push docker image to Amazon ECR # Private
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: dev-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Checkout Kubernetes manifests repository
      uses: actions/checkout@v3
      with:
        repository: $GITHUB_USERNAME/k8s-manifest-repo
        ref: main
        token: ${{ secrets.ACTION_TOKEN }}
        path: k8s-manifest-repo


    - name: Update Kubernetes resources
      run: |
        MANIFEST_PATH="k8s-manifest-repo/fe-be/fe-deployment.yaml" 
        NEW_IMAGE="${{ steps.login-ecr.outputs.registry}}/${{ steps.image-info.outputs.ecr_repository }}:${{ steps.image-info.outputs.image_tag }}"
        sed -i "s|${{ steps.login-ecr.outputs.registry}}/${{ steps.image-info.outputs.ecr_repository }}:.*|$NEW_IMAGE|" $MANIFEST_PATH
        cat $MANIFEST_PATH
    
    - name: Commit files
      run: |
        cd k8s-manifest-repo
        git config --global user.email "kshhhhh91@gmail.com"
        git config --global user.name "kshhhhh91"
        git commit -am "Update image tag"
        git push -u origin main
